### ISSUE TITLE
HDR+ artifacts on OP3

### ISSUE THREAD

**Issue by goosvorbook** [crashoverride1995/HEVC-Enabler-for-OP3T#1]
Hi Crashoverride1995,

I'm very happy with these patches, but recently it stopped working for HDR+ on my Oneplus 3.

It started showing colorful artifacts, but they only appear when HDR+ is started.

Any way to resolve this issue?
![photo_2018-01-09_22-17-23](https://user-images.githubusercontent.com/23636293/34868934-a28a64e4-f785-11e7-85ef-af7480c27e01.jpg)

**Comment by crashoverride1995** [comment]
This module doesn't even mess with HDR+. It's a problem with your Camera app not this module.

**Comment by goosvorbook** [comment]
Hey Crashoverride1995,

Thanks for the (very) quick reply.

Can you suggest me a google camera mod, that doesn't have this issue?
I used to be able to use HDR+, but since a couple of days it seems broken.
Could it potentially be an issue with LineageOS?

**Comment by crashoverride1995** [comment]
Check the modded google camera thread over at XDA.
